namespace Sonic.Definitions
{
  public static class Opcodes
  {
    public struct Opcode
    {
      public readonly Operation Operation;
      public readonly Operand Source;
      public readonly Operand Destination;

      public Opcode(Operation op, Operand src, Operand dst)
      {
        Operation = op;
        Source = src;
        Destination = dst;
      }
    }

    public static readonly byte[] Prefixes = new byte[] { 0xCB, 0xDD, 0xED ,0xFD };

    public static Opcode DecodeOpcode(byte p0, byte p1, byte op) => GetOpcodeTable(p0, p1)[op];

    public static Opcode[] GetOpcodeTable(byte prefix0, byte prefix1) => new { prefix0, prefix1 } switch
    {
      { prefix0: 0x00 } => _mainTable,
      { prefix0: 0xCB } => _bitTable,
      { prefix0: 0xDD, 
        prefix1: 0xCB } => _ixBitTable,
      { prefix0: 0xDD } => _ixTable,
      { prefix0: 0xED } => _miscTable,
      { prefix0: 0xFD, 
        prefix1: 0xCB } => _iyBitTable,
      { prefix0: 0xFD } => _iyTable,
      _ => throw new InvalidOperationException()
    };

    private static readonly Opcode[] _mainTable = new Opcode[]
    {
      new Opcode(Operation.NOP,   Operand.None,   Operand.None),
      new Opcode(Operation.LD,    Operand.BC,     Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.RLCA,  Operand.None,   Operand.None),  
      new Opcode(Operation.EX,    Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.RRCA,  Operand.None,   Operand.None),  
      new Opcode(Operation.DJNZ,  Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.RLA,   Operand.None,   Operand.None),  
      new Opcode(Operation.JR,    Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.RRA,   Operand.None,   Operand.None),
      new Opcode(Operation.JR,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.DAA,   Operand.None,   Operand.None),  
      new Opcode(Operation.JR,    Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.CPL,   Operand.None,   Operand.None),
      new Opcode(Operation.JR,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.SCF,   Operand.None,   Operand.None),  
      new Opcode(Operation.JR,    Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.INC,   Operand.None,   Operand.None),  
      new Opcode(Operation.DEC,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.CCF,   Operand.None,   Operand.None),     
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.HALT,  Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADC,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADC,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADC,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADC,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADC,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADC,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADC,   Operand.None,   Operand.None),  
      new Opcode(Operation.ADC,   Operand.None,   Operand.None),
      new Opcode(Operation.SUB,   Operand.None,   Operand.None),  
      new Opcode(Operation.SUB,   Operand.None,   Operand.None),  
      new Opcode(Operation.SUB,   Operand.None,   Operand.None),  
      new Opcode(Operation.SUB,   Operand.None,   Operand.None),  
      new Opcode(Operation.SUB,   Operand.None,   Operand.None),  
      new Opcode(Operation.SUB,   Operand.None,   Operand.None),  
      new Opcode(Operation.SUB,   Operand.None,   Operand.None),  
      new Opcode(Operation.SUB,   Operand.None,   Operand.None),  
      new Opcode(Operation.SBC,   Operand.None,   Operand.None),  
      new Opcode(Operation.SBC,   Operand.None,   Operand.None),  
      new Opcode(Operation.SBC,   Operand.None,   Operand.None),  
      new Opcode(Operation.SBC,   Operand.None,   Operand.None),  
      new Opcode(Operation.SBC,   Operand.None,   Operand.None),  
      new Opcode(Operation.SBC,   Operand.None,   Operand.None),  
      new Opcode(Operation.SBC,   Operand.None,   Operand.None),  
      new Opcode(Operation.SBC,   Operand.None,   Operand.None),
      new Opcode(Operation.AND,   Operand.None,   Operand.None),  
      new Opcode(Operation.AND,   Operand.None,   Operand.None),  
      new Opcode(Operation.AND,   Operand.None,   Operand.None),  
      new Opcode(Operation.AND,   Operand.None,   Operand.None),  
      new Opcode(Operation.AND,   Operand.None,   Operand.None),  
      new Opcode(Operation.AND,   Operand.None,   Operand.None),  
      new Opcode(Operation.AND,   Operand.None,   Operand.None),  
      new Opcode(Operation.AND,   Operand.None,   Operand.None),  
      new Opcode(Operation.XOR,   Operand.None,   Operand.None),  
      new Opcode(Operation.XOR,   Operand.None,   Operand.None),  
      new Opcode(Operation.XOR,   Operand.None,   Operand.None),  
      new Opcode(Operation.XOR,   Operand.None,   Operand.None),  
      new Opcode(Operation.XOR,   Operand.None,   Operand.None),  
      new Opcode(Operation.XOR,   Operand.None,   Operand.None),  
      new Opcode(Operation.XOR,   Operand.None,   Operand.None),  
      new Opcode(Operation.XOR,   Operand.None,   Operand.None),
      new Opcode(Operation.OR,    Operand.None,   Operand.None),  
      new Opcode(Operation.OR,    Operand.None,   Operand.None),  
      new Opcode(Operation.OR,    Operand.None,   Operand.None),  
      new Opcode(Operation.OR,    Operand.None,   Operand.None),  
      new Opcode(Operation.OR,    Operand.None,   Operand.None),  
      new Opcode(Operation.OR,    Operand.None,   Operand.None),  
      new Opcode(Operation.OR,    Operand.None,   Operand.None),  
      new Opcode(Operation.OR,    Operand.None,   Operand.None),  
      new Opcode(Operation.CP,    Operand.None,   Operand.None),  
      new Opcode(Operation.CP,    Operand.None,   Operand.None),  
      new Opcode(Operation.CP,    Operand.None,   Operand.None),  
      new Opcode(Operation.CP,    Operand.None,   Operand.None),  
      new Opcode(Operation.CP,    Operand.None,   Operand.None),  
      new Opcode(Operation.CP,    Operand.None,   Operand.None),  
      new Opcode(Operation.CP,    Operand.None,   Operand.None),  
      new Opcode(Operation.CP,    Operand.None,   Operand.None),
      new Opcode(Operation.RET,   Operand.None,   Operand.None),  
      new Opcode(Operation.POP,   Operand.None,   Operand.None),  
      new Opcode(Operation.JP,    Operand.None,   Operand.None),  
      new Opcode(Operation.JP,    Operand.None,   Operand.None),  
      new Opcode(Operation.CALL,  Operand.None,   Operand.None),  
      new Opcode(Operation.PUSH,  Operand.None,   Operand.None),  
      new Opcode(Operation.ADD,   Operand.None,   Operand.None),  
      new Opcode(Operation.RST,   Operand.None,   Operand.None),  
      new Opcode(Operation.RET,   Operand.None,   Operand.None),  
      new Opcode(Operation.RET,   Operand.None,   Operand.None),  
      new Opcode(Operation.JP,    Operand.None,   Operand.None),  
      new Opcode(Operation.NOP,   Operand.None,   Operand.None),  
      new Opcode(Operation.CALL,  Operand.None,   Operand.None),  
      new Opcode(Operation.CALL,  Operand.None,   Operand.None),  
      new Opcode(Operation.ADC,   Operand.None,   Operand.None),  
      new Opcode(Operation.RST,   Operand.None,   Operand.None),
      new Opcode(Operation.RET,   Operand.None,   Operand.None),  
      new Opcode(Operation.POP,   Operand.None,   Operand.None),  
      new Opcode(Operation.JP,    Operand.None,   Operand.None),  
      new Opcode(Operation.OUT,   Operand.None,   Operand.None),  
      new Opcode(Operation.CALL,  Operand.None,   Operand.None),  
      new Opcode(Operation.PUSH,  Operand.None,   Operand.None),  
      new Opcode(Operation.SUB,   Operand.None,   Operand.None),  
      new Opcode(Operation.RST,   Operand.None,   Operand.None),  
      new Opcode(Operation.RET,   Operand.None,   Operand.None),  
      new Opcode(Operation.EXX,   Operand.None,   Operand.None),  
      new Opcode(Operation.JP,    Operand.None,   Operand.None),  
      new Opcode(Operation.IN,    Operand.None,   Operand.None),  
      new Opcode(Operation.CALL,  Operand.None,   Operand.None),  
      new Opcode(Operation.NOP,   Operand.None,   Operand.None),  
      new Opcode(Operation.SBC,   Operand.None,   Operand.None),  
      new Opcode(Operation.RST,   Operand.None,   Operand.None),
      new Opcode(Operation.RET,   Operand.None,   Operand.None),  
      new Opcode(Operation.POP,   Operand.None,   Operand.None),  
      new Opcode(Operation.JP,    Operand.None,   Operand.None),  
      new Opcode(Operation.EX,    Operand.None,   Operand.None),  
      new Opcode(Operation.CALL,  Operand.None,   Operand.None),  
      new Opcode(Operation.PUSH,  Operand.None,   Operand.None),  
      new Opcode(Operation.AND,   Operand.None,   Operand.None),  
      new Opcode(Operation.RST,   Operand.None,   Operand.None),  
      new Opcode(Operation.RET,   Operand.None,   Operand.None),  
      new Opcode(Operation.JP,    Operand.None,   Operand.None),  
      new Opcode(Operation.JP,    Operand.None,   Operand.None),  
      new Opcode(Operation.EX,    Operand.None,   Operand.None),  
      new Opcode(Operation.CALL,  Operand.None,   Operand.None),  
      new Opcode(Operation.NOP,   Operand.None,   Operand.None),  
      new Opcode(Operation.XOR,   Operand.None,   Operand.None),  
      new Opcode(Operation.RST,   Operand.None,   Operand.None),
      new Opcode(Operation.RET,   Operand.None,   Operand.None),  
      new Opcode(Operation.POP,   Operand.None,   Operand.None),  
      new Opcode(Operation.JP,    Operand.None,   Operand.None),  
      new Opcode(Operation.DI,    Operand.None,   Operand.None),  
      new Opcode(Operation.CALL,  Operand.None,   Operand.None),  
      new Opcode(Operation.PUSH,  Operand.None,   Operand.None),  
      new Opcode(Operation.OR,    Operand.None,   Operand.None),  
      new Opcode(Operation.RST,   Operand.None,   Operand.None),  
      new Opcode(Operation.RET,   Operand.None,   Operand.None),  
      new Opcode(Operation.LD,    Operand.None,   Operand.None),  
      new Opcode(Operation.JP,    Operand.None,   Operand.None),  
      new Opcode(Operation.EI,    Operand.None,   Operand.None),  
      new Opcode(Operation.CALL,  Operand.None,   Operand.None),  
      new Opcode(Operation.NOP,   Operand.None,   Operand.None),  
      new Opcode(Operation.CP,    Operand.None,   Operand.None),  
      new Opcode(Operation.RST,   Operand.None,   Operand.None),
    };

    private static readonly Opcode[] _bitTable =
    { // 0         1         2         3         4         5         6         7         8         9         A         B         C         D         E         F
      Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RRC,   Operation.RRC,   Operation.RRC,   Operation.RRC,   Operation.RRC,   Operation.RRC,   Operation.RRC,   Operation.RRC,
      Operation.RL,    Operation.RL,    Operation.RL,    Operation.RL,    Operation.RL,    Operation.RL,    Operation.RL,    Operation.RL,    Operation.RR,    Operation.RR,    Operation.RR,    Operation.RR,    Operation.RR,    Operation.RR,    Operation.RR,    Operation.RR,
      Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SRA,   Operation.SRA,   Operation.SRA,   Operation.SRA,   Operation.SRA,   Operation.SRA,   Operation.SRA,   Operation.SRA,
      Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SRL,   Operation.SRL,   Operation.SRL,   Operation.SRL,   Operation.SRL,   Operation.SRL,   Operation.SRL,   Operation.SRL,
      Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT, 
      Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT, 
      Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT, 
      Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT, 
      Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,
      Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,
      Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,
      Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,
      Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,
      Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,
      Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,
      Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET
    };

    private static readonly Opcode[] _ixTable =
    { // 0         1         2         3         4         5         6         7         8         9         A         B         C         D         E         F
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.ADD,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP, 
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.ADD,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.LD,    Operation.LD,    Operation.INC,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.ADD,   Operation.LD,    Operation.DEC,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.INC,   Operation.DEC,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.ADD,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,
      Operation.LD,    Operation.LD,    Operation.LD,    Operation.LD,    Operation.LD,    Operation.LD,    Operation.NOP,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.ADD,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.ADC,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SUB,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SBC,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.AND,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.XOR,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.OR,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.CP,    Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.POP,   Operation.NOP,   Operation.EX,    Operation.NOP,   Operation.PUSH,  Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.JP,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP
    };

    private static readonly Opcode[] _ixBitTable =
    { // 0         1         2         3         4         5         6         7         8         9         A         B         C         D         E         F
      Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RLC,   Operation.RRC,   Operation.RRC,   Operation.RRC,   Operation.RRC,   Operation.RRC,   Operation.RRC,   Operation.RRC,   Operation.RRC,
      Operation.RL,    Operation.RL,    Operation.RL,    Operation.RL,    Operation.RL,    Operation.RL,    Operation.RL,    Operation.RL,    Operation.RR,    Operation.RR,    Operation.RR,    Operation.RR,    Operation.RR,    Operation.RR,    Operation.RR,    Operation.RR,
      Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SLA,   Operation.SRA,   Operation.SRA,   Operation.SRA,   Operation.SRA,   Operation.SRA,   Operation.SRA,   Operation.SRA,   Operation.SRA,
      Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SLL,   Operation.SRL,   Operation.SRL,   Operation.SRL,   Operation.SRL,   Operation.SRL,   Operation.SRL,   Operation.SRL,   Operation.SRL,
      Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT, 
      Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT, 
      Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT, 
      Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT,   Operation.BIT, 
      Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,
      Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,
      Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,
      Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,   Operation.RES,
      Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,
      Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,
      Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,
      Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET,   Operation.SET
    };
    
    private static readonly Opcode[] _miscTable = 
    { // 0         1         2         3         4         5         6         7         8         9         A         B         C         D         E         F
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.IN,    Operation.OUT,   Operation.SBC,   Operation.LD,    Operation.NEG,   Operation.RETN,  Operation.IM,    Operation.LD,    Operation.IN,    Operation.OUT,   Operation.ADC,   Operation.LD,    Operation.NOP,   Operation.RETI,  Operation.NOP,   Operation.LD,
      Operation.IN,    Operation.NOP,   Operation.SBC,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.IM,    Operation.LD,    Operation.IN,    Operation.OUT,   Operation.ADC,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.IM,    Operation.LD,
      Operation.IN,    Operation.NOP,   Operation.SBC,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RRD,   Operation.IN,    Operation.OUT,   Operation.ADC,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RLD,
      Operation.NOP,   Operation.NOP,   Operation.SBC,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.IN,    Operation.OUT,   Operation.ADC,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.LDI,   Operation.CPI,   Operation.INI,   Operation.OUTI,  Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LDD,   Operation.CPD,   Operation.IND,   Operation.OUTD,  Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.LDIR,  Operation.CPIR,  Operation.INIR,  Operation.OTIR,  Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LDDR,  Operation.CPDR,  Operation.INDR,  Operation.OTDR,  Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
    };
    
    private static readonly Opcode[] _iyTable = 
    { // 0         1         2         3         4         5         6         7         8         9         A         B         C         D         E         F
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.ADD,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.ADD,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.LD,    Operation.LD,    Operation.INC,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.ADD,   Operation.LD,    Operation.DEC,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.INC,   Operation.DEC,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.ADD,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,
      Operation.LD,    Operation.LD,    Operation.LD,    Operation.LD,    Operation.LD,    Operation.LD,    Operation.NOP,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.ADD,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.ADC,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SUB,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SBC,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.AND,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.XOR,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.OR,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.CP,    Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.POP,   Operation.NOP,   Operation.EX,    Operation.NOP,   Operation.PUSH,  Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.JP,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.LD,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP
    };
    
    private static readonly Opcode[] _iyBitTable = 
    { // 0         1         2         3         4         5         6         7         8         9         A         B         C         D         E         F
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RLC,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RRC,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RL,    Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RR,    Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SLA,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SRA,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SRL,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.BIT,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.BIT,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.BIT,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.BIT,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.BIT,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.BIT,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.BIT,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.BIT,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RES,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RES,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RES,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RES,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RES,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RES,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RES,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.RES,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SET,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SET,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SET,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SET,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SET,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SET,   Operation.NOP,
      Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SET,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.NOP,   Operation.SET,   Operation.NOP
    };
  }
}