<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <RollForward>Major</RollForward>
    <PublishAot>true</PublishAot>
    <OptimizationPreference>Speed</OptimizationPreference>
    <TieredCompilation>true</TieredCompilation>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <PropertyGroup>
    <ApplicationIcon>../assets/icon.ico</ApplicationIcon>
    <ApplicationManifest>../app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="../assets/icon.bmp">
      <IncludeInSingleFile>true</IncludeInSingleFile>
      <LogicalName>icon.bmp</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="../assets/icon.ico">
      <IncludeInSingleFile>true</IncludeInSingleFile>
      <LogicalName>icon.ico</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="../assets/icon.rgba">
      <IncludeInSingleFile>true</IncludeInSingleFile>
      <LogicalName>icon.rgba</LogicalName>
    </EmbeddedResource>
    <None Include="..\bios.sms" Condition="Exists('..\bios.sms')">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      <CopyToPublishDirectory>Always</CopyToPublishDirectory>
    </None>
    <None Include="..\config.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MessagePack" Version="3.1.7" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="System.IO.Hashing" Version="10.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <NoWarn>CS0282,CA1869,CS8509</NoWarn>
  </PropertyGroup>

</Project>