using System.Runtime.CompilerServices;

namespace Quill.Definitions
{
  public unsafe static class Opcodes
  {
    public readonly struct Opcode
    {
      public readonly Operation Operation;
      public readonly Operand Destination;
      public readonly Operand Source;
      public readonly byte Cycles;

      public Opcode() 
        : this(Operation.NOP, 4) {}

      public Opcode(Operation op, byte cycles) 
        : this(op, Operand.Implied, cycles) {}

      public Opcode(Operation op, Operand dst, byte cycles) 
        : this(op, dst, Operand.Implied, cycles) {}

      public Opcode(Operation op, Operand dst, Operand src, byte cycles)
      {
        Operation = op;
        Destination = dst;
        Source = src;
        Cycles = cycles;
      }

      [MethodImpl(MethodImplOptions.AggressiveInlining)]
      public bool IsWordOperation() => _wordOperands.Contains(Destination) ||
                                       _wordOperands.Contains(Source);

      public override string ToString() => $"{Operation} {Destination},{Source}";
    }

    private static readonly Operand[] _wordOperands = new Operand[]
    {      
      Operand.AF, 
      Operand.BC, 
      Operand.DE, 
      Operand.HL, 
      Operand.IX,  
      Operand.IY, 
      Operand.SP
    };

    public static readonly Opcode[] Main = new Opcode[]
    {
      // Opcodes 0x00 - 0x0F
      new Opcode(Operation.NOP,   Operand.Implied,    Operand.Implied,     4),
      new Opcode(Operation.LD,    Operand.BC,         Operand.Immediate,  10),
      new Opcode(Operation.LD,    Operand.BCi,        Operand.A,           7),
      new Opcode(Operation.INC,   Operand.BC,         Operand.Implied,     6),
      new Opcode(Operation.INC,   Operand.B,          Operand.Implied,     4),
      new Opcode(Operation.DEC,   Operand.B,          Operand.Implied,     4),
      new Opcode(Operation.LD,    Operand.B,          Operand.Immediate,   7),
      new Opcode(Operation.RLCA,  Operand.Implied,    Operand.Implied,     4),
      new Opcode(Operation.EX,    Operand.AF,         Operand.Implied,     4),
      new Opcode(Operation.ADD,   Operand.HL,         Operand.BC,         11),
      new Opcode(Operation.LD,    Operand.A,          Operand.BCi,         7),
      new Opcode(Operation.DEC,   Operand.BC,         Operand.Implied,     6),
      new Opcode(Operation.INC,   Operand.C,          Operand.Implied,     4),
      new Opcode(Operation.DEC,   Operand.C,          Operand.Implied,     4),
      new Opcode(Operation.LD,    Operand.C,          Operand.Immediate,   7),
      new Opcode(Operation.RRCA,  Operand.Implied,    Operand.Implied,     4),

      // Opcodes 0x10 - 0x1F
      new Opcode(Operation.DJNZ,  Operand.Implied,    Operand.Implied,     8),
      new Opcode(Operation.LD,    Operand.DE,         Operand.Immediate,  10),
      new Opcode(Operation.LD,    Operand.DEi,        Operand.A,           7),
      new Opcode(Operation.INC,   Operand.DE,         Operand.Implied,     6),
      new Opcode(Operation.INC,   Operand.D,          Operand.Implied,     4),
      new Opcode(Operation.DEC,   Operand.D,          Operand.Implied,     4),
      new Opcode(Operation.LD,    Operand.D,          Operand.Immediate,   7),
      new Opcode(Operation.RLA,   Operand.Implied,    Operand.Implied,     4),
      new Opcode(Operation.JR,    Operand.Implied,    Operand.Implied,    12),
      new Opcode(Operation.ADD,   Operand.HL,         Operand.DE,         11),
      new Opcode(Operation.LD,    Operand.A,          Operand.DEi,         7),
      new Opcode(Operation.DEC,   Operand.DE,         Operand.Implied,     6),
      new Opcode(Operation.INC,   Operand.E,          Operand.Implied,     4),
      new Opcode(Operation.DEC,   Operand.E,          Operand.Implied,     4),
      new Opcode(Operation.LD,    Operand.E,          Operand.Immediate,   7),
      new Opcode(Operation.RRA,   Operand.Implied,    Operand.Implied,     4),

      // Opcodes 0x20 - 0x2F
      new Opcode(Operation.JR,    Operand.NonZero,    Operand.Implied,     7),
      new Opcode(Operation.LD,    Operand.DE,         Operand.Immediate,  10),
      new Opcode(Operation.LD,    Operand.DEi,        Operand.A,          16),
      new Opcode(Operation.INC,   Operand.DE,         Operand.Implied,     6),
      new Opcode(Operation.INC,   Operand.D,          Operand.Implied,     4),
      new Opcode(Operation.DEC,   Operand.D,          Operand.Implied,     4),
      new Opcode(Operation.LD,    Operand.D,          Operand.Immediate,   7),
      new Opcode(Operation.DAA,   Operand.Implied,    Operand.Implied,     4),
      new Opcode(Operation.JR,    Operand.Zero,       Operand.Implied,     7),
      new Opcode(Operation.ADD,   Operand.HL,         Operand.HL,         11),
      new Opcode(Operation.LD,    Operand.HL,         Operand.Indirect,   16),
      new Opcode(Operation.DEC,   Operand.HL,         Operand.Implied,     6),
      new Opcode(Operation.INC,   Operand.L,          Operand.Implied,     4),
      new Opcode(Operation.DEC,   Operand.L,          Operand.Implied,     4),
      new Opcode(Operation.LD,    Operand.L,          Operand.Immediate,   7),
      new Opcode(Operation.CPL,   Operand.Implied,    Operand.Implied,     4),
        
      // Opcodes 0x30 - 0x3F  
      new Opcode(Operation.JR,    Operand.NonCarry,   Operand.Implied,     7),
      new Opcode(Operation.LD,    Operand.SP,         Operand.Immediate,  10),
      new Opcode(Operation.LD,    Operand.Indirect,   Operand.A,          13),
      new Opcode(Operation.INC,   Operand.SP,         Operand.Implied,     6),
      new Opcode(Operation.INC,   Operand.HLi,        Operand.Implied,    11),
      new Opcode(Operation.DEC,   Operand.HLi,        Operand.Implied,    11),
      new Opcode(Operation.LD,    Operand.HLi,        Operand.Immediate,  10),
      new Opcode(Operation.SCF,   Operand.Implied,    Operand.Implied,     4),
      new Opcode(Operation.JR,    Operand.C,          Operand.Implied,     7),
      new Opcode(Operation.ADD,   Operand.HL,         Operand.SP,         11),
      new Opcode(Operation.LD,    Operand.A,          Operand.Indirect,   13),
      new Opcode(Operation.DEC,   Operand.SP,         Operand.Implied,     6),
      new Opcode(Operation.INC,   Operand.A,          Operand.Implied,     4),
      new Opcode(Operation.DEC,   Operand.A,          Operand.Implied,     4),
      new Opcode(Operation.LD,    Operand.A,          Operand.Immediate,   7),
      new Opcode(Operation.CCF,   Operand.Implied,    Operand.Implied,     4),
      
      // Opcodes 0x40 - 0x4F
      new Opcode(),
      new Opcode(Operation.LD,    Operand.B,          Operand.C,           4),
      new Opcode(Operation.LD,    Operand.B,          Operand.D,           4),
      new Opcode(Operation.LD,    Operand.B,          Operand.E,           4),
      new Opcode(Operation.LD,    Operand.B,          Operand.H,           4),
      new Opcode(Operation.LD,    Operand.B,          Operand.L,           4),
      new Opcode(Operation.LD,    Operand.B,          Operand.HLi,         7),
      new Opcode(Operation.LD,    Operand.B,          Operand.A,           4),
      new Opcode(Operation.LD,    Operand.C,          Operand.B,           4),
      new Opcode(), 
      new Opcode(Operation.LD,    Operand.C,          Operand.D,           4),
      new Opcode(Operation.LD,    Operand.C,          Operand.E,           4),
      new Opcode(Operation.LD,    Operand.C,          Operand.H,           4),
      new Opcode(Operation.LD,    Operand.C,          Operand.L,           4),
      new Opcode(Operation.LD,    Operand.C,          Operand.HLi,         7),
      new Opcode(Operation.LD,    Operand.C,          Operand.A,           4),

      // Opcodes 0x50 - 0x5F    
      new Opcode(Operation.LD,    Operand.D,          Operand.B,           4),
      new Opcode(Operation.LD,    Operand.D,          Operand.C,           4),
      new Opcode(), 
      new Opcode(Operation.LD,    Operand.D,          Operand.E,           4),
      new Opcode(Operation.LD,    Operand.D,          Operand.H,           4),
      new Opcode(Operation.LD,    Operand.D,          Operand.L,           4),
      new Opcode(Operation.LD,    Operand.D,          Operand.HLi,         7),
      new Opcode(Operation.LD,    Operand.D,          Operand.A,           4),
      new Opcode(Operation.LD,    Operand.E,          Operand.B,           4),
      new Opcode(Operation.LD,    Operand.E,          Operand.C,           4),
      new Opcode(Operation.LD,    Operand.E,          Operand.D,           4),
      new Opcode(), 
      new Opcode(Operation.LD,    Operand.E,          Operand.H,           4),
      new Opcode(Operation.LD,    Operand.E,          Operand.L,           4),
      new Opcode(Operation.LD,    Operand.E,          Operand.HLi,         7),
      new Opcode(Operation.LD,    Operand.E,          Operand.A,           4),

      // Opcodes 0x60 - 0x6F    
      new Opcode(Operation.LD,    Operand.H,          Operand.B,           4),
      new Opcode(Operation.LD,    Operand.H,          Operand.C,           4),
      new Opcode(Operation.LD,    Operand.H,          Operand.D,           4),
      new Opcode(Operation.LD,    Operand.H,          Operand.E,           4),
      new Opcode(), 
      new Opcode(Operation.LD,    Operand.H,          Operand.L,           4),
      new Opcode(Operation.LD,    Operand.H,          Operand.HLi,         7),
      new Opcode(Operation.LD,    Operand.H,          Operand.A,           4),
      new Opcode(Operation.LD,    Operand.L,          Operand.B,           4),
      new Opcode(Operation.LD,    Operand.L,          Operand.C,           4),
      new Opcode(Operation.LD,    Operand.L,          Operand.D,           4),
      new Opcode(Operation.LD,    Operand.L,          Operand.E,           4),
      new Opcode(Operation.LD,    Operand.L,          Operand.H,           4),
      new Opcode(), 
      new Opcode(Operation.LD,    Operand.L,          Operand.HLi,         7),
      new Opcode(Operation.LD,    Operand.L,          Operand.A,           4),

      // Opcodes 0x70 - 0x7F    
      new Opcode(Operation.LD,    Operand.HLi,        Operand.B,           7),
      new Opcode(Operation.LD,    Operand.HLi,        Operand.C,           7),
      new Opcode(Operation.LD,    Operand.HLi,        Operand.D,           7),
      new Opcode(Operation.LD,    Operand.HLi,        Operand.E,           7),
      new Opcode(Operation.LD,    Operand.HLi,        Operand.H,           7),
      new Opcode(Operation.LD,    Operand.HLi,        Operand.L,           7),
      new Opcode(Operation.HALT,  Operand.Implied,    Operand.Implied,     4),
      new Opcode(Operation.LD,    Operand.HLi,        Operand.A,           7),
      new Opcode(Operation.LD,    Operand.A,          Operand.B,           4),
      new Opcode(Operation.LD,    Operand.A,          Operand.C,           4),
      new Opcode(Operation.LD,    Operand.A,          Operand.D,           4),
      new Opcode(Operation.LD,    Operand.A,          Operand.E,           4),
      new Opcode(Operation.LD,    Operand.A,          Operand.H,           4),
      new Opcode(Operation.LD,    Operand.A,          Operand.L,           4),
      new Opcode(Operation.LD,    Operand.A,          Operand.HLi,         7),
      new Opcode(), 

      // Opcodes 0x80 - 0x8F    
      new Opcode(Operation.ADD,   Operand.A,          Operand.B,           4),
      new Opcode(Operation.ADD,   Operand.A,          Operand.C,           4),
      new Opcode(Operation.ADD,   Operand.A,          Operand.D,           4),
      new Opcode(Operation.ADD,   Operand.A,          Operand.E,           4),
      new Opcode(Operation.ADD,   Operand.A,          Operand.H,           4),
      new Opcode(Operation.ADD,   Operand.A,          Operand.L,           4),
      new Opcode(Operation.ADD,   Operand.A,          Operand.HLi,         7),
      new Opcode(Operation.ADD,   Operand.A,          Operand.A,           4),
      new Opcode(Operation.ADC,   Operand.A,          Operand.B,           4),
      new Opcode(Operation.ADC,   Operand.A,          Operand.C,           4),
      new Opcode(Operation.ADC,   Operand.A,          Operand.D,           4),
      new Opcode(Operation.ADC,   Operand.A,          Operand.E,           4),
      new Opcode(Operation.ADC,   Operand.A,          Operand.H,           4),
      new Opcode(Operation.ADC,   Operand.A,          Operand.L,           4),
      new Opcode(Operation.ADC,   Operand.A,          Operand.HLi,         7),
      new Opcode(Operation.ADC,   Operand.A,          Operand.A,           4),

      // Opcodes 0x90 - 0x9F  
      new Opcode(Operation.SUB,  Operand.Implied,     Operand.B,           4),
      new Opcode(Operation.SUB,  Operand.Implied,     Operand.C,           4),
      new Opcode(Operation.SUB,  Operand.Implied,     Operand.D,           4),
      new Opcode(Operation.SUB,  Operand.Implied,     Operand.E,           4),
      new Opcode(Operation.SUB,  Operand.Implied,     Operand.H,           4),
      new Opcode(Operation.SUB,  Operand.Implied,     Operand.L,           4),
      new Opcode(Operation.SUB,  Operand.Implied,     Operand.HLi,         7),
      new Opcode(Operation.SUB,  Operand.Implied,     Operand.A,           4),
      new Opcode(Operation.SBC,  Operand.A,           Operand.B,           4),
      new Opcode(Operation.SBC,  Operand.A,           Operand.C,           4),
      new Opcode(Operation.SBC,  Operand.A,           Operand.D,           4),
      new Opcode(Operation.SBC,  Operand.A,           Operand.E,           4),
      new Opcode(Operation.SBC,  Operand.A,           Operand.H,           4),
      new Opcode(Operation.SBC,  Operand.A,           Operand.L,           4),
      new Opcode(Operation.SBC,  Operand.A,           Operand.HLi,         7),
      new Opcode(Operation.SBC,  Operand.A,           Operand.A,           4),
 
      // Opcodes 0xA0 - 0xAF   
      new Opcode(Operation.AND,  Operand.Implied,     Operand.B,           4),
      new Opcode(Operation.AND,  Operand.Implied,     Operand.C,           4),
      new Opcode(Operation.AND,  Operand.Implied,     Operand.D,           4),
      new Opcode(Operation.AND,  Operand.Implied,     Operand.E,           4),
      new Opcode(Operation.AND,  Operand.Implied,     Operand.H,           4),
      new Opcode(Operation.AND,  Operand.Implied,     Operand.L,           4),
      new Opcode(Operation.AND,  Operand.Implied,     Operand.HLi,         7),
      new Opcode(Operation.AND,  Operand.Implied,     Operand.A,           4),
      new Opcode(Operation.XOR,  Operand.Implied,     Operand.B,           4),
      new Opcode(Operation.XOR,  Operand.Implied,     Operand.C,           4),
      new Opcode(Operation.XOR,  Operand.Implied,     Operand.D,           4),
      new Opcode(Operation.XOR,  Operand.Implied,     Operand.E,           4),
      new Opcode(Operation.XOR,  Operand.Implied,     Operand.H,           4),
      new Opcode(Operation.XOR,  Operand.Implied,     Operand.L,           4),
      new Opcode(Operation.XOR,  Operand.Implied,     Operand.HLi,         7),
      new Opcode(Operation.XOR,  Operand.Implied,     Operand.A,           4),
 
      // Opcodes 0xB0 - 0xBF   
      new Opcode(Operation.OR,   Operand.Implied,     Operand.B,           4),
      new Opcode(Operation.OR,   Operand.Implied,     Operand.C,           4),
      new Opcode(Operation.OR,   Operand.Implied,     Operand.D,           4),
      new Opcode(Operation.OR,   Operand.Implied,     Operand.E,           4),
      new Opcode(Operation.OR,   Operand.Implied,     Operand.H,           4),
      new Opcode(Operation.OR,   Operand.Implied,     Operand.L,           4),
      new Opcode(Operation.OR,   Operand.Implied,     Operand.HLi,         7),
      new Opcode(Operation.OR,   Operand.Implied,     Operand.A,           4),
      new Opcode(Operation.CP,   Operand.Implied,     Operand.B,           4),
      new Opcode(Operation.CP,   Operand.Implied,     Operand.C,           4),
      new Opcode(Operation.CP,   Operand.Implied,     Operand.D,           4),
      new Opcode(Operation.CP,   Operand.Implied,     Operand.E,           4),
      new Opcode(Operation.CP,   Operand.Implied,     Operand.H,           4),
      new Opcode(Operation.CP,   Operand.Implied,     Operand.L,           4),
      new Opcode(Operation.CP,   Operand.Implied,     Operand.HLi,         7),
      new Opcode(Operation.CP,   Operand.Implied,     Operand.A,           4),
 
      // Opcodes 0xC0 - 0xCF   
      new Opcode(Operation.RET,  Operand.NonZero,     Operand.Implied,     5),
      new Opcode(Operation.POP,  Operand.BC,          Operand.Implied,    10),
      new Opcode(Operation.JP,   Operand.NonZero,     Operand.Immediate,  10),
      new Opcode(Operation.JP,   Operand.Implied,     Operand.Immediate,  10),
      new Opcode(Operation.CALL, Operand.NonZero,     Operand.Immediate,  10),
      new Opcode(Operation.PUSH, Operand.Implied,     Operand.BC,         11),
      new Opcode(Operation.ADD,  Operand.A,           Operand.Immediate,   7),
      new Opcode(Operation.RST,  Operand.RST0,        Operand.Implied,    11),
      new Opcode(Operation.RET,  Operand.Zero,        Operand.Implied,     5),
      new Opcode(Operation.RET,  Operand.Implied,     Operand.Implied,    10),
      new Opcode(Operation.JP,   Operand.Zero,        Operand.Immediate,  10),
      new Opcode(),  
      new Opcode(Operation.CALL, Operand.Zero,        Operand.Immediate,  10),
      new Opcode(Operation.CALL, Operand.Implied,     Operand.Immediate,  17),
      new Opcode(Operation.ADC,  Operand.A,           Operand.Immediate,   7),
      new Opcode(Operation.RST,  Operand.RST1,        Operand.Implied,    11),
 
      // Opcodes 0xD0 - 0xDF   
      new Opcode(Operation.RET,  Operand.NonCarry,    Operand.Implied,     5),
      new Opcode(Operation.POP,  Operand.DE,          Operand.Implied,    10),
      new Opcode(Operation.JP,   Operand.NonCarry,    Operand.Immediate,  10),
      new Opcode(Operation.OUT,  Operand.Immediate,   Operand.A,          11),
      new Opcode(Operation.CALL, Operand.NonCarry,    Operand.Immediate,  10),
      new Opcode(Operation.PUSH, Operand.Implied,     Operand.DE,         11),
      new Opcode(Operation.SUB,  Operand.Implied,     Operand.Immediate,   7),
      new Opcode(Operation.RST,  Operand.RST2,        Operand.Implied,    11),
      new Opcode(Operation.RET,  Operand.Carry,       Operand.Implied,     5),
      new Opcode(Operation.EXX,  Operand.Implied,     Operand.Implied,     4),
      new Opcode(Operation.JP,   Operand.Carry,       Operand.Immediate,  10),
      new Opcode(Operation.IN,   Operand.A,           Operand.Immediate,  11),
      new Opcode(Operation.CALL, Operand.Carry,       Operand.Immediate,  10),
      new Opcode(), 
      new Opcode(Operation.SBC,  Operand.A,           Operand.Immediate,   7),
      new Opcode(Operation.RST,  Operand.RST3,        Operand.Implied,    11),
 
      // Opcodes 0xE0 - 0xEF   
      new Opcode(Operation.RET,  Operand.Even,        Operand.Implied,     5),
      new Opcode(Operation.POP,  Operand.HL,          Operand.Implied,    10),
      new Opcode(Operation.JP,   Operand.Even,        Operand.Immediate,  10),
      new Opcode(Operation.EX,   Operand.SP,          Operand.HL,         19),
      new Opcode(Operation.CALL, Operand.Even,        Operand.Immediate,  10),
      new Opcode(Operation.PUSH, Operand.Implied,     Operand.HL,         11),
      new Opcode(Operation.AND,  Operand.Implied,     Operand.Implied,     7),
      new Opcode(Operation.RST,  Operand.RST4,        Operand.Implied,    11),
      new Opcode(Operation.RET,  Operand.Implied,     Operand.Implied,     5),
      new Opcode(Operation.JP,   Operand.Implied,     Operand.Implied,     4),
      new Opcode(Operation.JP,   Operand.Even,        Operand.Immediate,  10),
      new Opcode(Operation.EX,   Operand.DE,          Operand.HL,          4),
      new Opcode(Operation.CALL, Operand.Even,        Operand.Immediate,  10),
      new Opcode(),  
      new Opcode(Operation.XOR,  Operand.Implied,     Operand.Immediate,   7),
      new Opcode(Operation.RST,  Operand.RST5,        Operand.Implied,    11),
 
      // Opcodes 0xF0 - 0xFF   
      new Opcode(Operation.RET,  Operand.Positive,    Operand.Implied,     5),
      new Opcode(Operation.POP,  Operand.AF,          Operand.Implied,    10),
      new Opcode(Operation.JP,   Operand.Positive,    Operand.Immediate,  10),
      new Opcode(Operation.DI,   Operand.Implied,     Operand.Implied,     4),
      new Opcode(Operation.CALL, Operand.Positive,    Operand.Immediate,  10),
      new Opcode(Operation.PUSH, Operand.Implied,     Operand.AF,         11),
      new Opcode(Operation.OR,   Operand.Implied,     Operand.Immediate,   7),
      new Opcode(Operation.RST,  Operand.RST6,        Operand.Implied,    11),
      new Opcode(Operation.RET,  Operand.Negative,    Operand.Implied,     5),
      new Opcode(Operation.LD,   Operand.SP,          Operand.HL,          6),
      new Opcode(Operation.JP,   Operand.Negative,    Operand.Implied,    10),
      new Opcode(Operation.EI,   Operand.Implied,     Operand.Implied,     4),
      new Opcode(Operation.CALL, Operand.Negative,    Operand.Immediate,  10),
      new Opcode(), 
      new Opcode(Operation.CP,   Operand.Implied,     Operand.Immediate,   7),
      new Opcode(Operation.RST,  Operand.RST7,        Operand.Implied,    11),
    };

    public static readonly Opcode[] CB = new Opcode[]
    {
      // Opcodes 0x00 - 0x0F
      new Opcode(Operation.RLC,   Operand.B,          Operand.Implied,     8),
      new Opcode(Operation.RLC,   Operand.C,          Operand.Implied,     8),
      new Opcode(Operation.RLC,   Operand.D,          Operand.Implied,     8),
      new Opcode(Operation.RLC,   Operand.E,          Operand.Implied,     8),
      new Opcode(Operation.RLC,   Operand.H,          Operand.Implied,     8),
      new Opcode(Operation.RLC,   Operand.L,          Operand.Implied,     8),
      new Opcode(Operation.RLC,   Operand.HLi,        Operand.Implied,    15),
      new Opcode(Operation.RLC,   Operand.A,          Operand.Implied,     8),
      new Opcode(Operation.RRC,   Operand.B,          Operand.Implied,     8),
      new Opcode(Operation.RRC,   Operand.C,          Operand.Implied,     8),
      new Opcode(Operation.RRC,   Operand.D,          Operand.Implied,     8),
      new Opcode(Operation.RRC,   Operand.E,          Operand.Implied,     8),
      new Opcode(Operation.RRC,   Operand.H,          Operand.Implied,     8),
      new Opcode(Operation.RRC,   Operand.L,          Operand.Implied,     8),
      new Opcode(Operation.RRC,   Operand.HLi,        Operand.Implied,    15),
      new Opcode(Operation.RRC,   Operand.A,          Operand.Implied,     8),

      // Opcodes 0x10 - 0x1F
      new Opcode(Operation.RL,    Operand.B,          Operand.Implied,     8),
      new Opcode(Operation.RL,    Operand.C,          Operand.Implied,     8),
      new Opcode(Operation.RL,    Operand.D,          Operand.Implied,     8),
      new Opcode(Operation.RL,    Operand.E,          Operand.Implied,     8),
      new Opcode(Operation.RL,    Operand.H,          Operand.Implied,     8),
      new Opcode(Operation.RL,    Operand.L,          Operand.Implied,     8),
      new Opcode(Operation.RL,    Operand.HLi,        Operand.Implied,    15),
      new Opcode(Operation.RL,    Operand.A,          Operand.Implied,     8),
      new Opcode(Operation.RR,    Operand.B,          Operand.Implied,     8),
      new Opcode(Operation.RR,    Operand.C,          Operand.Implied,     8),
      new Opcode(Operation.RR,    Operand.D,          Operand.Implied,     8),
      new Opcode(Operation.RR,    Operand.E,          Operand.Implied,     8),
      new Opcode(Operation.RR,    Operand.H,          Operand.Implied,     8),
      new Opcode(Operation.RR,    Operand.L,          Operand.Implied,     8),
      new Opcode(Operation.RR,    Operand.HLi,        Operand.Implied,    15),
      new Opcode(Operation.RR,    Operand.A,          Operand.Implied,     8),
 
      // Opcodes 0x20 - 0x2F 
      new Opcode(Operation.SLA,   Operand.B,          Operand.Implied,     8),
      new Opcode(Operation.SLA,   Operand.C,          Operand.Implied,     8),
      new Opcode(Operation.SLA,   Operand.D,          Operand.Implied,     8),
      new Opcode(Operation.SLA,   Operand.E,          Operand.Implied,     8),
      new Opcode(Operation.SLA,   Operand.H,          Operand.Implied,     8),
      new Opcode(Operation.SLA,   Operand.L,          Operand.Implied,     8),
      new Opcode(Operation.SLA,   Operand.HLi,        Operand.Implied,    15),
      new Opcode(Operation.SLA,   Operand.A,          Operand.Implied,     8),
      new Opcode(Operation.SRA,   Operand.B,          Operand.Implied,     8),
      new Opcode(Operation.SRA,   Operand.C,          Operand.Implied,     8),
      new Opcode(Operation.SRA,   Operand.D,          Operand.Implied,     8),
      new Opcode(Operation.SRA,   Operand.E,          Operand.Implied,     8),
      new Opcode(Operation.SRA,   Operand.H,          Operand.Implied,     8),
      new Opcode(Operation.SRA,   Operand.L,          Operand.Implied,     8),
      new Opcode(Operation.SRA,   Operand.HLi,        Operand.Implied,    15),
      new Opcode(Operation.SRA,   Operand.A,          Operand.Implied,     8),
        
      // Opcodes 0x30 - 0x3F  
      new Opcode(Operation.SLL,   Operand.B,          Operand.Implied,     8),
      new Opcode(Operation.SLL,   Operand.C,          Operand.Implied,     8),
      new Opcode(Operation.SLL,   Operand.D,          Operand.Implied,     8),
      new Opcode(Operation.SLL,   Operand.E,          Operand.Implied,     8),
      new Opcode(Operation.SLL,   Operand.H,          Operand.Implied,     8),
      new Opcode(Operation.SLL,   Operand.L,          Operand.Implied,     8),
      new Opcode(Operation.SLL,   Operand.HLi,        Operand.Implied,    15),
      new Opcode(Operation.SLL,   Operand.A,          Operand.Implied,     8),
      new Opcode(Operation.SRL,   Operand.B,          Operand.Implied,     8),
      new Opcode(Operation.SRL,   Operand.C,          Operand.Implied,     8),
      new Opcode(Operation.SRL,   Operand.D,          Operand.Implied,     8),
      new Opcode(Operation.SRL,   Operand.E,          Operand.Implied,     8),
      new Opcode(Operation.SRL,   Operand.H,          Operand.Implied,     8),
      new Opcode(Operation.SRL,   Operand.L,          Operand.Implied,     8),
      new Opcode(Operation.SRL,   Operand.HLi,        Operand.Implied,    15),
      new Opcode(Operation.SRL,   Operand.A,          Operand.Implied,     8),
      
      // Opcodes 0x40 - 0x4F 
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.B,           8),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.C,           8),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.D,           8),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.E,           8),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.H,           8),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.L,           8),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.HLi,        12),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.A,           8),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.B,           8),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.C,           8),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.D,           8),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.E,           8),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.H,           8),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.L,           8),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.HLi,        12),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.A,           8),
      
      // Opcodes 0x50 - 0x5F 
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.B,           8),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.C,           8),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.D,           8),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.E,           8),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.H,           8),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.L,           8),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.HLi,        12),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.A,           8),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.B,           8),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.C,           8),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.D,           8),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.E,           8),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.H,           8),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.L,           8),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.HLi,        12),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.A,           8),
      
      // Opcodes 0x60 - 0x6F 
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.B,           8),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.C,           8),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.D,           8),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.E,           8),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.H,           8),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.L,           8),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.HLi,        12),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.A,           8),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.B,           8),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.C,           8),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.D,           8),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.E,           8),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.H,           8),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.L,           8),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.HLi,        12),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.A,           8),
      
      // Opcodes 0x70 - 0x7F 
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.B,           8),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.C,           8),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.D,           8),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.E,           8),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.H,           8),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.L,           8),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.HLi,        12),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.A,           8),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.B,           8),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.C,           8),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.D,           8),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.E,           8),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.H,           8),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.L,           8),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.HLi,        12),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.A,           8),
      
      // Opcodes 0x80 - 0x8F 
      new Opcode(Operation.RES,   (Operand) 0,        Operand.B,           8),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.C,           8),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.D,           8),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.E,           8),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.H,           8),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.L,           8),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.HLi,        15),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.A,           8),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.B,           8),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.C,           8),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.D,           8),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.E,           8),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.H,           8),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.L,           8),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.HLi,        15),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.A,           8),

      // Opcodes 0x90 - 0x9F 
      new Opcode(Operation.RES,   (Operand) 2,        Operand.B,           8),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.C,           8),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.D,           8),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.E,           8),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.H,           8),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.L,           8),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.HLi,        15),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.A,           8),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.B,           8),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.C,           8),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.D,           8),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.E,           8),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.H,           8),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.L,           8),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.HLi,        15),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.A,           8),
      
      // Opcodes 0xA0 - 0xAF 
      new Opcode(Operation.RES,   (Operand) 4,        Operand.B,           8),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.C,           8),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.D,           8),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.E,           8),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.H,           8),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.L,           8),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.HLi,        15),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.A,           8),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.B,           8),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.C,           8),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.D,           8),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.E,           8),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.H,           8),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.L,           8),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.HLi,        15),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.A,           8),

      // Opcodes 0xB0 - 0xBF 
      new Opcode(Operation.RES,   (Operand) 6,        Operand.B,           8),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.C,           8),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.D,           8),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.E,           8),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.H,           8),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.L,           8),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.HLi,        15),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.A,           8),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.B,           8),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.C,           8),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.D,           8),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.E,           8),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.H,           8),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.L,           8),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.HLi,        15),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.A,           8),

      // Opcodes 0xC0 - 0xCF 
      new Opcode(Operation.SET,   (Operand) 0,        Operand.B,           8),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.C,           8),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.D,           8),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.E,           8),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.H,           8),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.L,           8),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.HLi,        15),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.A,           8),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.B,           8),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.C,           8),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.D,           8),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.E,           8),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.H,           8),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.L,           8),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.HLi,        15),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.A,           8),

      // Opcodes 0xD0 - 0xDF 
      new Opcode(Operation.SET,   (Operand) 2,        Operand.B,           8),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.C,           8),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.D,           8),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.E,           8),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.H,           8),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.L,           8),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.HLi,        15),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.A,           8),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.B,           8),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.C,           8),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.D,           8),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.E,           8),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.H,           8),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.L,           8),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.HLi,        15),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.A,           8),

      // Opcodes 0xE0 - 0xEF 
      new Opcode(Operation.SET,   (Operand) 4,        Operand.B,           8),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.C,           8),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.D,           8),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.E,           8),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.H,           8),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.L,           8),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.HLi,        15),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.A,           8),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.B,           8),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.C,           8),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.D,           8),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.E,           8),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.H,           8),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.L,           8),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.HLi,        15),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.A,           8),

      // Opcodes 0xF0 - 0xFF 
      new Opcode(Operation.SET,   (Operand) 6,        Operand.B,           8),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.C,           8),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.D,           8),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.E,           8),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.H,           8),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.L,           8),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.HLi,        15),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.A,           8),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.B,           8),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.C,           8),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.D,           8),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.E,           8),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.H,           8),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.L,           8),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.HLi,        15),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.A,           8),
    };

    public static readonly Opcode[] DD = new Opcode[]
    {
      // // Opcodes 0x00 - 0x0F
      // new Opcode(),
      // new Opcode(),  
      // new Opcode(),
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(Operation.ADD,  Operand.IX,         Operand.BC),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(), 
  
      // // Opcodes 0x10 - 0x1F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.ADD,  Operand.IX,         Operand.DE),  
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),

      // // Opcodes 0x20 - 0x2F
      // new Opcode(),  
      // new Opcode(Operation.LD,   Operand.IX,         Operand.Immediate),  
      // new Opcode(Operation.LD,   Operand.Indirect,   Operand.IX),
      // new Opcode(Operation.INC,  Operand.IX,         Operand.Implied), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(),
      // new Opcode(), 
      // new Opcode(),  
      // new Opcode(Operation.ADD,  Operand.IX,         Operand.IX),  
      // new Opcode(Operation.LD,   Operand.IX,         Operand.Indirect),
      // new Opcode(Operation.DEC,  Operand.IX,         Operand.Implied), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(),

      // // Opcodes 0x30 - 0x3F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.INC,  Operand.IXd,        Operand.Implied),
      // new Opcode(Operation.DEC,  Operand.IXd,        Operand.Implied),
      // new Opcode(Operation.LD,   Operand.IXd,        Operand.Immediate),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.ADD,  Operand.IX,         Operand.SP),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),

      // // Opcodes 0x40 - 0x4F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.B,          Operand.IXd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.C,          Operand.IXd),
      // new Opcode(),

      // // Opcodes 0x50 - 0x5F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.D,          Operand.IXd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.E,          Operand.IXd),
      // new Opcode(),

      // // Opcodes 0x60 - 0x6F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.H,          Operand.IXd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.L,          Operand.IXd),
      // new Opcode(),

      // // Opcodes 0x70 - 0x7F
      // new Opcode(Operation.LD,   Operand.IXd,        Operand.B),  
      // new Opcode(Operation.LD,   Operand.IXd,        Operand.C),  
      // new Opcode(Operation.LD,   Operand.IXd,        Operand.D),  
      // new Opcode(Operation.LD,   Operand.IXd,        Operand.E),  
      // new Opcode(Operation.LD,   Operand.IXd,        Operand.H),  
      // new Opcode(Operation.LD,   Operand.IXd,        Operand.L),  
      // new Opcode(),  
      // new Opcode(Operation.LD,   Operand.IXd,        Operand.A),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.A,          Operand.IXd),  
      // new Opcode(),

      // // Opcodes 0x80 - 0x8F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.ADD,  Operand.A,          Operand.IXd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.ADC,  Operand.A,          Operand.IXd),
      // new Opcode(),

      // // Opcodes 0x90 - 0x9F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.SUB,  Operand.Implied,    Operand.IXd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.SBC,  Operand.A,          Operand.IXd),
      // new Opcode(),

      // // Opcodes 0xA0 - 0xAF
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.AND,  Operand.Implied,    Operand.IXd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.XOR,  Operand.Implied,    Operand.IXd),
      // new Opcode(),

      // // Opcodes 0xB0 - 0xBF
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.OR,   Operand.Implied,    Operand.IXd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.CP,   Operand.Implied,    Operand.IXd),
      // new Opcode(),

      // // Opcodes 0xC0 - 0xCF
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(),

      // // Opcodes 0xD0 - 0xDF
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(),

      // // Opcodes 0xE0 - 0xEF
      // new Opcode(),
      // new Opcode(Operation.POP,   Operand.IX,         Operand.Implied),
      // new Opcode(),
      // new Opcode(Operation.EX,    Operand.SP,         Operand.IX),
      // new Opcode(),
      // new Opcode(Operation.PUSH,  Operand.Implied,    Operand.IX),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.JP,    Operand.Implied,    Operand.IX),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),

      // // Opcodes 0xF0 - 0xFF
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,    Operand.SP,         Operand.IX),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode()
    };
    
    public static readonly Opcode[] DDCB = new Opcode[]
    {
      // Opcodes 0x00 - 0x0F
      new Opcode(Operation.RLC,   Operand.IXd,        Operand.B,         23),
      new Opcode(Operation.RLC,   Operand.IXd,        Operand.C,         23),
      new Opcode(Operation.RLC,   Operand.IXd,        Operand.D,         23),
      new Opcode(Operation.RLC,   Operand.IXd,        Operand.E,         23),
      new Opcode(Operation.RLC,   Operand.IXd,        Operand.H,         23),
      new Opcode(Operation.RLC,   Operand.IXd,        Operand.L,         23),
      new Opcode(Operation.RLC,   Operand.IXd,        Operand.Implied,   23),
      new Opcode(Operation.RLC,   Operand.IXd,        Operand.A,         23),
      new Opcode(Operation.RRC,   Operand.IXd,        Operand.B,         23),
      new Opcode(Operation.RRC,   Operand.IXd,        Operand.C,         23),
      new Opcode(Operation.RRC,   Operand.IXd,        Operand.D,         23),
      new Opcode(Operation.RRC,   Operand.IXd,        Operand.E,         23),
      new Opcode(Operation.RRC,   Operand.IXd,        Operand.H,         23),
      new Opcode(Operation.RRC,   Operand.IXd,        Operand.L,         23),
      new Opcode(Operation.RRC,   Operand.IXd,        Operand.Implied,   23),
      new Opcode(Operation.RRC,   Operand.IXd,        Operand.A,         23),

      // Opcodes 0x10 - 0x1F
      new Opcode(Operation.RL,    Operand.IXd,        Operand.B,         23),
      new Opcode(Operation.RL,    Operand.IXd,        Operand.C,         23),
      new Opcode(Operation.RL,    Operand.IXd,        Operand.D,         23),
      new Opcode(Operation.RL,    Operand.IXd,        Operand.E,         23),
      new Opcode(Operation.RL,    Operand.IXd,        Operand.H,         23),
      new Opcode(Operation.RL,    Operand.IXd,        Operand.L,         23),
      new Opcode(Operation.RL,    Operand.IXd,        Operand.Implied,   23),
      new Opcode(Operation.RL,    Operand.IXd,        Operand.A,         23),
      new Opcode(Operation.RR,    Operand.IXd,        Operand.B,         23),
      new Opcode(Operation.RR,    Operand.IXd,        Operand.C,         23),
      new Opcode(Operation.RR,    Operand.IXd,        Operand.D,         23),
      new Opcode(Operation.RR,    Operand.IXd,        Operand.E,         23),
      new Opcode(Operation.RR,    Operand.IXd,        Operand.H,         23),
      new Opcode(Operation.RR,    Operand.IXd,        Operand.L,         23),
      new Opcode(Operation.RR,    Operand.IXd,        Operand.Implied,   23),
      new Opcode(Operation.RR,    Operand.IXd,        Operand.A,         23),
 
      // Opcodes 0x20 - 0x2F 
      new Opcode(Operation.SLA,   Operand.IXd,        Operand.B,         23),
      new Opcode(Operation.SLA,   Operand.IXd,        Operand.C,         23),
      new Opcode(Operation.SLA,   Operand.IXd,        Operand.D,         23),
      new Opcode(Operation.SLA,   Operand.IXd,        Operand.E,         23),
      new Opcode(Operation.SLA,   Operand.IXd,        Operand.H,         23),
      new Opcode(Operation.SLA,   Operand.IXd,        Operand.L,         23),
      new Opcode(Operation.SLA,   Operand.IXd,        Operand.Implied,   23),
      new Opcode(Operation.SLA,   Operand.IXd,        Operand.A,         23),
      new Opcode(Operation.SRA,   Operand.IXd,        Operand.B,         23),
      new Opcode(Operation.SRA,   Operand.IXd,        Operand.C,         23),
      new Opcode(Operation.SRA,   Operand.IXd,        Operand.D,         23),
      new Opcode(Operation.SRA,   Operand.IXd,        Operand.E,         23),
      new Opcode(Operation.SRA,   Operand.IXd,        Operand.H,         23),
      new Opcode(Operation.SRA,   Operand.IXd,        Operand.L,         23),
      new Opcode(Operation.SRA,   Operand.IXd,        Operand.Implied,   23),
      new Opcode(Operation.SRA,   Operand.IXd,        Operand.A,         23),
        
      // Opcodes 0x30 - 0x3F  
      new Opcode(Operation.SLL,   Operand.IXd,        Operand.B,         23),
      new Opcode(Operation.SLL,   Operand.IXd,        Operand.C,         23),
      new Opcode(Operation.SLL,   Operand.IXd,        Operand.D,         23),
      new Opcode(Operation.SLL,   Operand.IXd,        Operand.E,         23),
      new Opcode(Operation.SLL,   Operand.IXd,        Operand.H,         23),
      new Opcode(Operation.SLL,   Operand.IXd,        Operand.L,         23),
      new Opcode(Operation.SLL,   Operand.IXd,        Operand.Implied,   23),
      new Opcode(Operation.SLL,   Operand.IXd,        Operand.A,         23),
      new Opcode(Operation.SRL,   Operand.IXd,        Operand.B,         23),
      new Opcode(Operation.SRL,   Operand.IXd,        Operand.C,         23),
      new Opcode(Operation.SRL,   Operand.IXd,        Operand.D,         23),
      new Opcode(Operation.SRL,   Operand.IXd,        Operand.E,         23),
      new Opcode(Operation.SRL,   Operand.IXd,        Operand.H,         23),
      new Opcode(Operation.SRL,   Operand.IXd,        Operand.L,         23),
      new Opcode(Operation.SRL,   Operand.IXd,        Operand.Implied,   23),
      new Opcode(Operation.SRL,   Operand.IXd,        Operand.A,         23),
      
      // Opcodes 0x40 - 0x4F 
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 0,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 1,        Operand.IXd,       20),
      
      // Opcodes 0x50 - 0x5F 
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 2,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 3,        Operand.IXd,       20),
      
      // Opcodes 0x60 - 0x6F 
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 4,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 5,        Operand.IXd,       20),
      
      // Opcodes 0x70 - 0x7F 
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 6,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.IXd,       20),
      new Opcode(Operation.BIT,   (Operand) 7,        Operand.IXd,       20),
      
      // Opcodes 0x80 - 0x8F 
      new Opcode(Operation.RES,   (Operand) 0,        Operand.B,         23),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.C,         23),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.D,         23),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.E,         23),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.H,         23),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.L,         23),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.Implied,   23),
      new Opcode(Operation.RES,   (Operand) 0,        Operand.A,         23),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.B,         23),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.C,         23),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.D,         23),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.E,         23),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.H,         23),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.L,         23),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.Implied,   23),
      new Opcode(Operation.RES,   (Operand) 1,        Operand.A,         23),

      // Opcodes 0x90 - 0x9F 
      new Opcode(Operation.RES,   (Operand) 2,        Operand.B,         23),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.C,         23),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.D,         23),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.E,         23),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.H,         23),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.L,         23),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.Implied,   23),
      new Opcode(Operation.RES,   (Operand) 2,        Operand.A,         23),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.B,         23),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.C,         23),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.D,         23),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.E,         23),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.H,         23),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.L,         23),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.Implied,   23),
      new Opcode(Operation.RES,   (Operand) 3,        Operand.A,         23),
      
      // Opcodes 0xA0 - 0xAF 
      new Opcode(Operation.RES,   (Operand) 4,        Operand.B,         23),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.C,         23),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.D,         23),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.E,         23),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.H,         23),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.L,         23),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.Implied,   23),
      new Opcode(Operation.RES,   (Operand) 4,        Operand.A,         23),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.B,         23),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.C,         23),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.D,         23),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.E,         23),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.H,         23),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.L,         23),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.Implied,   23),
      new Opcode(Operation.RES,   (Operand) 5,        Operand.A,         23),

      // Opcodes 0xB0 - 0xBF 
      new Opcode(Operation.RES,   (Operand) 6,        Operand.B,         23),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.C,         23),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.D,         23),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.E,         23),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.H,         23),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.L,         23),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.Implied,   23),
      new Opcode(Operation.RES,   (Operand) 6,        Operand.A,         23),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.B,         23),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.C,         23),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.D,         23),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.E,         23),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.H,         23),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.L,         23),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.Implied,   23),
      new Opcode(Operation.RES,   (Operand) 7,        Operand.A,         23),

      // Opcodes 0xC0 - 0xCF 
      new Opcode(Operation.SET,   (Operand) 0,        Operand.B,         23),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.C,         23),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.D,         23),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.E,         23),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.H,         23),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.L,         23),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.Implied,   23),
      new Opcode(Operation.SET,   (Operand) 0,        Operand.A,         23),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.B,         23),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.C,         23),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.D,         23),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.E,         23),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.H,         23),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.L,         23),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.Implied,   23),
      new Opcode(Operation.SET,   (Operand) 1,        Operand.A,         23),

      // Opcodes 0xD0 - 0xDF 
      new Opcode(Operation.SET,   (Operand) 2,        Operand.B,         23),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.C,         23),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.D,         23),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.E,         23),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.H,         23),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.L,         23),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.Implied,   23),
      new Opcode(Operation.SET,   (Operand) 2,        Operand.A,         23),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.B,         23),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.C,         23),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.D,         23),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.E,         23),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.H,         23),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.L,         23),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.Implied,   23),
      new Opcode(Operation.SET,   (Operand) 3,        Operand.A,         23),

      // Opcodes 0xE0 - 0xEF 
      new Opcode(Operation.SET,   (Operand) 4,        Operand.B,         23),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.C,         23),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.D,         23),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.E,         23),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.H,         23),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.L,         23),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.Implied,   23),
      new Opcode(Operation.SET,   (Operand) 4,        Operand.A,         23),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.B,         23),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.C,         23),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.D,         23),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.E,         23),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.H,         23),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.L,         23),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.Implied,   23),
      new Opcode(Operation.SET,   (Operand) 5,        Operand.A,         23),

      // Opcodes 0xF0 - 0xFF 
      new Opcode(Operation.SET,   (Operand) 6,        Operand.B,         23),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.C,         23),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.D,         23),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.E,         23),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.H,         23),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.L,         23),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.Implied,   23),
      new Opcode(Operation.SET,   (Operand) 6,        Operand.A,         23),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.B,         23),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.C,         23),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.D,         23),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.E,         23),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.H,         23),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.L,         23),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.Implied,   23),
      new Opcode(Operation.SET,   (Operand) 7,        Operand.A,         23),
    };
    
    public static readonly Opcode[] ED = new Opcode[]
    {
      // Opcodes 0x00 - 0x0F
      new Opcode(),
      new Opcode(),
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),
      
      // Opcodes 0x10 - 0x1F
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),

      // Opcodes 0x20 - 0x2F
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),

      // Opcodes 0x30 - 0x3F
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),

      // Opcodes 0x40 - 0x4F
      new Opcode(Operation.IN,    Operand.B,          Operand.C,         12),
      new Opcode(Operation.OUT,   Operand.C,          Operand.B,         12),
      new Opcode(Operation.SBC,   Operand.HL,         Operand.BC,        15),
      new Opcode(Operation.LD,    Operand.Indirect,   Operand.BC,        20),
      new Opcode(Operation.NEG,   Operand.Implied,    Operand.Implied,    8),
      new Opcode(Operation.RETN,  Operand.Implied,    Operand.Implied,   14),
      new Opcode(Operation.IM,    (Operand) 0,        Operand.Implied,    8),
      new Opcode(Operation.LD,    Operand.I,          Operand.A,          9),
      new Opcode(Operation.IN,    Operand.C,          Operand.C,         12),
      new Opcode(Operation.OUT,   Operand.C,          Operand.C,         12),
      new Opcode(Operation.ADC,   Operand.HL,         Operand.BC,        15),
      new Opcode(Operation.LD,    Operand.BC,         Operand.Indirect,  20),
      new Opcode(),  
      new Opcode(Operation.RETI,  Operand.Implied,    Operand.Implied,   14),
      new Opcode(),  
      new Opcode(Operation.LD,    Operand.R,          Operand.A,          9),

      // Opcodes 0x50 - 0x5F
      new Opcode(Operation.IN,    Operand.D,          Operand.C,         12),
      new Opcode(Operation.OUT,   Operand.C,          Operand.D,         12),
      new Opcode(Operation.SBC,   Operand.HL,         Operand.DE,        15),
      new Opcode(Operation.LD,    Operand.Indirect,   Operand.DE,        20),
      new Opcode(),   
      new Opcode(),   
      new Opcode(Operation.IM,    (Operand) 1,        Operand.Implied,    8),
      new Opcode(Operation.LD,    Operand.A,          Operand.I,          9),
      new Opcode(Operation.IN,    Operand.E,          Operand.C,         12),
      new Opcode(Operation.OUT,   Operand.C,          Operand.E,         12),
      new Opcode(Operation.ADC,   Operand.HL,         Operand.DE,        15),
      new Opcode(Operation.LD,    Operand.DE,         Operand.Indirect,  20),
      new Opcode(),   
      new Opcode(),   
      new Opcode(Operation.IM,    (Operand) 2,        Operand.Implied,    8),
      new Opcode(Operation.LD,    Operand.A,          Operand.R,          9),

      // Opcodes 0x60 - 0x6F
      new Opcode(Operation.IN,    Operand.H,          Operand.C,         12),
      new Opcode(Operation.OUT,   Operand.C,          Operand.H,         12),
      new Opcode(Operation.SBC,   Operand.HL,         Operand.HL,        15),
      new Opcode(Operation.LD,    Operand.Indirect,   Operand.HL,        20),
      new Opcode(),   
      new Opcode(),   
      new Opcode(),   
      new Opcode(Operation.RRD,   Operand.Implied,    Operand.Implied,   18),
      new Opcode(Operation.IN,    Operand.L,          Operand.C,         12),
      new Opcode(Operation.OUT,   Operand.C,          Operand.L,         12),
      new Opcode(Operation.ADC,   Operand.HL,         Operand.HL,        15),
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(Operation.RLD,   Operand.Implied,    Operand.Implied,   18),

      // Opcodes 0x70 - 0x7F
      new Opcode(Operation.IN,    Operand.L,          Operand.C,         12),
      new Opcode(Operation.IN,    Operand.L,          Operand.C,         12),
      new Opcode(Operation.SBC,   Operand.HL,         Operand.SP,        15),
      new Opcode(Operation.LD,    Operand.Indirect,   Operand.SP,        20),
      new Opcode(),   
      new Opcode(),   
      new Opcode(),   
      new Opcode(),   
      new Opcode(Operation.IN,    Operand.A,          Operand.C,         12),
      new Opcode(Operation.OUT,   Operand.C,          Operand.A,         12),
      new Opcode(Operation.ADC,   Operand.HL,         Operand.SP,        15),
      new Opcode(Operation.LD,    Operand.SP,         Operand.Indirect,  20),
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),

      // Opcodes 0x80 - 0x8F
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),

      // Opcodes 0x90 - 0x9F
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),

      // Opcodes 0xA0 - 0xAF
      new Opcode(Operation.LDI,   Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.CPI,   Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.INI,   Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.OUTI,  Operand.Implied,    Operand.Implied,   16),
      new Opcode(),   
      new Opcode(),   
      new Opcode(),   
      new Opcode(),   
      new Opcode(Operation.LDD,   Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.CPD,   Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.IND,   Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.OUTD,  Operand.Implied,    Operand.Implied,   16),
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),

      // Opcodes 0xB0 - 0xBF
      new Opcode(Operation.LDIR,  Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.CPIR,  Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.INIR,  Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.OTIR,  Operand.Implied,    Operand.Implied,   16),
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode(Operation.LDDR,  Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.CPDR,  Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.INDR,  Operand.Implied,    Operand.Implied,   16),
      new Opcode(Operation.OTDR,  Operand.Implied,    Operand.Implied,   16),
      new Opcode(),  
      new Opcode(),  
      new Opcode(),  
      new Opcode()
    };
    
    public static readonly Opcode[] FD = new Opcode[]
    {
      // // Opcodes 0x00 - 0x0F
      // new Opcode(),
      // new Opcode(),  
      // new Opcode(),
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(Operation.ADD,  Operand.IY,         Operand.BC),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(),  
      // new Opcode(), 
  
      // // Opcodes 0x10 - 0x1F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.ADD,  Operand.IY,         Operand.DE),  
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),

      // // Opcodes 0x20 - 0x2F
      // new Opcode(),  
      // new Opcode(Operation.LD,   Operand.IY,         Operand.Immediate),  
      // new Opcode(Operation.LD,   Operand.Indirect,   Operand.IY),
      // new Opcode(Operation.INC,  Operand.IY,         Operand.Implied), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(),
      // new Opcode(), 
      // new Opcode(),  
      // new Opcode(Operation.ADD,  Operand.IY,         Operand.IY),  
      // new Opcode(Operation.LD,   Operand.IY,         Operand.Indirect),
      // new Opcode(Operation.DEC,  Operand.IY,         Operand.Implied), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(),

      // // Opcodes 0x30 - 0x3F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.INC,  Operand.IYd,        Operand.Implied),
      // new Opcode(Operation.DEC,  Operand.IYd,        Operand.Implied),
      // new Opcode(Operation.LD,   Operand.IYd,        Operand.Immediate),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.ADD,  Operand.IY,         Operand.SP),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),

      // // Opcodes 0x40 - 0x4F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.B,          Operand.IYd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.C,          Operand.IYd),
      // new Opcode(),

      // // Opcodes 0x50 - 0x5F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.D,          Operand.IYd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.E,          Operand.IYd),
      // new Opcode(),

      // // Opcodes 0x60 - 0x6F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.H,          Operand.IYd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.L,          Operand.IYd),
      // new Opcode(),

      // // Opcodes 0x70 - 0x7F
      // new Opcode(Operation.LD,   Operand.IYd,        Operand.B),  
      // new Opcode(Operation.LD,   Operand.IYd,        Operand.C),  
      // new Opcode(Operation.LD,   Operand.IYd,        Operand.D),  
      // new Opcode(Operation.LD,   Operand.IYd,        Operand.E),  
      // new Opcode(Operation.LD,   Operand.IYd,        Operand.H),  
      // new Opcode(Operation.LD,   Operand.IYd,        Operand.L),  
      // new Opcode(),  
      // new Opcode(Operation.LD,   Operand.IYd,        Operand.A),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.A,          Operand.IYd),  
      // new Opcode(),

      // // Opcodes 0x80 - 0x8F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.ADD,  Operand.A,          Operand.IYd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.ADC,  Operand.A,          Operand.IYd),
      // new Opcode(),

      // // Opcodes 0x90 - 0x9F
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.SUB,  Operand.Implied,    Operand.IYd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.SBC,  Operand.A,          Operand.IYd),
      // new Opcode(),

      // // Opcodes 0xA0 - 0xAF
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.AND,  Operand.Implied,    Operand.IYd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.XOR,  Operand.Implied,    Operand.IYd),
      // new Opcode(),

      // // Opcodes 0xB0 - 0xBF
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.OR,   Operand.Implied,    Operand.IYd),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.CP,   Operand.Implied,    Operand.IYd),
      // new Opcode(),

      // // Opcodes 0xC0 - 0xCF
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(),

      // // Opcodes 0xD0 - 0xDF
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(), 
      // new Opcode(),

      // // Opcodes 0xE0 - 0xEF
      // new Opcode(),
      // new Opcode(Operation.POP,  Operand.IY,         Operand.Implied),
      // new Opcode(),
      // new Opcode(Operation.EX,   Operand.SP,         Operand.IY),
      // new Opcode(),
      // new Opcode(Operation.PUSH, Operand.Implied,    Operand.IY),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.JP,   Operand.Implied,    Operand.IY),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),

      // // Opcodes 0xF0 - 0xFF
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(Operation.LD,   Operand.SP,         Operand.IY),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode(),
      // new Opcode()
    };
    
    public static readonly Opcode[] FDCB = new Opcode[]
    {
      // Copy from DDCB
    };
  }
}